[NCL-6588] implement archive endpoint
project-ncl/repository-driver pull request #12
Opened 2021-09-30 10:28 UTC by michalovjan

2021-09-30 10:43 UTC, michalovjan commented
this PR requires https://github.com/project-ncl/pnc-api/pull/57

2021-09-30 12:24 UTC, matejonnet commented on pom.xml
>    </repositories>
Why commenting this out ?

2021-09-30 13:43 UTC, michalovjan commented on pom.xml
>    </repositories>
forced pushed the fix

2021-10-01 08:34 UTC, pkocandr requested changes

2021-10-01 08:34 UTC, pkocandr commented on src/main/java/org/jboss/pnc/repositorydriver/endpoints/Public.java
> +            @QueryParam("seal") @DefaultValue("false") boolean seal) throws RepositoryDriverException {
Is this just for transition period or is there a valid use case where we want to do the seal during promotion?

2021-10-04 08:57 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/endpoints/Public.java
> +            @QueryParam("seal") @DefaultValue("false") boolean seal) throws RepositoryDriverException {
It's just a transition period.

2021-10-04 08:58 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +                .header("Authentication", "Bearer " + serviceTokens.getAccessToken());
Ohhh good catch!

2021-10-04 08:59 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +    public void seal(RepositoryPromoteRequest promoteRequest) throws RepositoryDriverException {
I wanted to keep it the same but I don't remember my reasoning. I'll create a new dto in pnc-api.

2021-10-04 09:34 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +        retrieveTrackingReport(buildContentId, true);
Thank you!

2021-10-04 09:56 UTC, pkocandr approved these changes
Looks good!

2021-10-04 11:00 UTC, michalovjan commented
retest this please

2021-12-10 18:12 UTC, pkocandr commented
retest this please

2022-01-06 14:51 UTC, pkocandr approved these changes
Just minor things, but I'm ok with merging it like this.

2022-01-06 15:33 UTC, michalovjan commented on pom.xml
> +      <artifactId>wiremock-jre8</artifactId>
The artifact is just a victim of bad naming :D It is actually java8+.

2022-01-06 15:44 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/ArchiveDownloadEntry.java
> +    private static StoreKey getStoreKeyFromTargetRepository(TargetRepository targetRepository) {
I don't mind the change

2022-01-06 15:56 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +        HttpRequest.Builder builder = HttpRequest.newBuilder()
This will practically never happen as we control that DTO. 

But theoretically:
If we don't run the request, then the process will get stuck on promotion and never recover... But the promotion may still succeed and leave us with version mismatches between PNC and Indy. So the question is whether we want stuck process or silent success. I guess stuck process would at least notify us that something may be wrong.

And BTW, this is not a new part of code (just git thinking it is).

2022-01-06 16:38 UTC, merged