[NCL-6845] change log level to WARN on failed promotion validation
project-ncl/repository-driver pull request #24
Opened 2022-01-20 14:37 UTC by michalovjan

2022-01-20 16:14 UTC, pkocandr requested changes

2022-01-20 16:14 UTC, pkocandr commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +                if (e instanceof RepositoryDriverException) {
Wouldn't it be better to separate the catch? It doesn't make sense to catch 2 exceptions in single catch and then have different handling for each of them.

2022-01-25 10:25 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Driver.java
> +                if (e instanceof RepositoryDriverException) {
that's absolutely correct

2022-01-25 11:13 UTC, pkocandr approved these changes

2022-01-25 11:16 UTC, merged