[NCL-8679] add filter archive entries by repo
project-ncl/repository-driver pull request #265
Opened 2024-05-28 14:44 UTC by michalovjan

Also I've moved the `repository-driver.ignored-repo-patterns` key to `repository-driver.ignored-repo-patterns.promotion` so that it is similar to `repository-driver.ignored-path-patterns.*` now that we have separate entries for archive requests.

2024-05-30 08:04 UTC, pkocandr requested changes

2024-05-30 08:04 UTC, pkocandr commented on src/main/java/org/jboss/pnc/repositorydriver/artifactfilter/ArtifactFilterArchive.java
> +                && !ignoredRepoPatterns.matchesOne(storeKey.toString());
Why is this not part of the ignoreContent method?

2024-05-30 08:27 UTC, pkocandr commented on src/main/java/org/jboss/pnc/repositorydriver/artifactfilter/ArtifactFilterArchive.java
> +                && !ignoredRepoPatterns.matchesOne(storeKey.toString());
Hmm, re-thinking this - if we consider only artifacts as the content, then it is probably correct to separate the repo check from the content check. :-)

2024-06-03 08:46 UTC, michalovjan commented on src/main/java/org/jboss/pnc/repositorydriver/Configuration.java
> +    Optional<List<String>> ignoredRepoPatternsArchive;
Will do!

2024-06-03 12:06 UTC, pkocandr approved these changes
Looks good now (except for the one extra line because of which the jenkins build fails :-) )

2024-06-03 12:49 UTC, merged